; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27034.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\i5\AppData\Local\Temp\.NETFramework,Version=v4.5.AssemblyAttributes.cpp"
